### ISSUE TITLE
Interrupt 8 timer tick reset handling could increment midnight flag

### ISSUE THREAD

**Issue by ecm-pushbx** [640-KB/GLaBIOS#21]
https://github.com/640-KB/GLaBIOS/blob/0d215eb173f2802de3dd4ec66d2d9934e068e4dd/src/GLABIOS.ASM#L10500

There's an extension to have the interrupt handler increment the day expired / midnight flag rather than set it to 1. This can help avoid missing a day if the time is not queried from interrupt 1Ah for as long as a day. (Plus, it saves a byte of code.)

**Comment by 640-KB** [comment]
> https://github.com/640-KB/GLaBIOS/blob/0d215eb173f2802de3dd4ec66d2d9934e068e4dd/src/GLABIOS.ASM#L10500
> 
> There's an extension to have the interrupt handler increment the day expired / midnight flag rather than set it to 1. This can help avoid missing a day if the time is not queried from interrupt 1Ah for as long as a day. (Plus, it saves a byte of code.)

Oooh, I like saving a byte!  I have a vague recollection that I actually tried that initially and it made the DOS clock go berserk (like it started showing time multiple times too fast).

Okay, I'm going to try that and will report back!

**Comment by ecm-pushbx** [comment]
> On the surface, it seems that incrementing the MF rather than setting to 1 has no immediately obvious problems. Most references I've ever seen though describe `40:70` as a "flag" rather than a counter. Do you know of any "authoritative" references that document that > 1 is a valid state?

In the interrupt list: http://fd.lod.bz/rbil/interrup/bios/1a00.html

**Comment by 640-KB** [comment]
> > On the surface, it seems that incrementing the MF rather than setting to 1 has no immediately obvious problems. Most references I've ever seen though describe `40:70` as a "flag" rather than a counter. Do you know of any "authoritative" references that document that > 1 is a valid state?
> 
> In the interrupt list: http://fd.lod.bz/rbil/interrup/bios/1a00.html

Perfect. That does clearly describe the behavior and the fact that DOS created a switches flag shows that the behavior is well-understood and defined by DOS, which was my question.  

I've changed this in my development tree and will continue testing, so this will be included in the next public commit.

Thanks again so much for the info and the idea!

640KB
