### ISSUE TITLE
Smaller (32K) BIOS and ROM files for NuXT

### ISSUE THREAD

**Issue by ConiKost** [640-KB/GLaBIOS#29]
Currently, 128KB images are offered, which can be flashed on the whole EEPROM. While this is a nice thing, I would like to see also smaller 32K images. AFAICS, you cannot flash those 128KB images via software on the NuXT itself. And if flashed externally, the whole EEPROM is programmed.

NuXT has a 128KB EEPROM, which is controlled via DIP switch, aka "dual BIOS". ON = First 64KB, OFF = Last 64KB. As 64KB can't be flashed at once, it must be divided into 2x32KB, 32KB for BIOS and 32KB for ROM. Flashing those 32KB files makes it possible to flash them via uflash in DOS. If a BIOS/ROM is smaller than 32KB, the rest up to 32768 Bytes is filled up with FF.

See manual, which describes this: https://raw.githubusercontent.com/monotech/NuXTv2/master/Monotech%20NuXT%202.0%20User%20Manual.pdf

Using smaller 32K images, it makes possible to flash them and for example, use ON=GlaDOS and OFF=Micro8080_Bios, so you can toggle between two BIOS variants.

**Comment by 640-KB** [comment]
I believe the 128K images had the default NuXT 8088 BIOS in the last 64KB and the GLaBIOS in the first (that's what I used to flash my 39SF010A), just for convenience.    No problem at all to break them up though -- will do so going forward!

640KB

**Comment by ConiKost** [comment]
Great, thank you!

**Comment by 640-KB** [comment]
@ConiKost the 32KiB images have been added to the [Releases page](https://github.com/640-KB/GLaBIOS/releases).  I've tested them myself with UFLASH and work great.

Thank you for the suggestion!

**Comment by ConiKost** [comment]
Thank you! :-)
