### ISSUE TITLE
Question about TD3300A

### ISSUE THREAD

**Issue by charlysan** [640-KB/GLaBIOS#33]
Is there some documentation available for `TD3300A` or everything used here (e.g. reg 0x90 usage) has been accomplished by reverse engineering juko's BIOS?

**Comment by 640-KB** [comment]
I covered most of this in the [VCFed reply](https://forum.vcfed.org/index.php?threads/xt-motherboard-identification.1242673/post-1310266).  To summarize, no datasheet has been found, however what is known come from the following sources:

#### Port `070h` 

Controls the wait state for board RAM, ROM, I/O and also bus RAM and I/O.  See (page B-1, B-2) from the [UX-12 manual](https://minuszerodegrees.net/manuals/Unique/Unique%20-%20UX%20Turbo%20Mainboard%20(44256%20version)%20-%20Users%20Manual.pdf).

#### Port `090h`

Controls the clock speed using the following:

 If port 90h == 1, send 2 (0010b) for Normal -> Turbo
 If port 90h == 0, send 3 (0011b) for Turbo -> Normal

#### Port `0E0h`

Controls the bank switching for the on-board upper memory, as mentioned in [this post](https://www.vogons.org/viewtopic.php?p=1015796#p1015796).

 if port 0Eh == 0, addresses `2000:0000`-`9000:FFFF` are mapped to the low contiguous RAM
 if port 0Eh == 1, addresses `2000:0000`-`9000:FFFF` are mapped to the upper RAM (if installed)

Also, here is an [unofficial document](https://www.vogons.org/viewtopic.php?p=1113190#p1113190) explaining these in more detail (in Cyrillic).
