### ISSUE TITLE
Auto detect max memory (736k)

### ISSUE THREAD

**Issue by andreas-jonsson** [640-KB/GLaBIOS#36]
Hi!

Thank you very much for creating this. It would be impossible of us working on downstream emulators to create out of the box opensource emulators without projects like this. <3

If I could wish for something it would be the ability to auto detect the max memory size. (above 640k)

Right now it is a compile flag controlling it. But it would be cool if the 736kb could be detected automatically. (as an option)
I think this would be possible by first look at the switches and detect EGA/VGA, then determine if there is a MDA or CGA card by testing some IO registers. Perhaps a simple r/w test.

If this was supported we would not have to ship multiple builds of the BIOS. :)

Thanks again!

**Comment by 640-KB** [comment]
Hmm... that's an interesting idea.  I'd think the jumpers might be the safest way to do it since it gives the user the ability to choose.  The only situation that comes to mind might be if you have both a CGA and MDA adapter installed but you select MDA as your primary adapter - of course that's why it would be a build option so you would only use it if it was desired.

Are you using the "emulator" build right now?  Perhaps making it the default for that could make some sense since.

I'll take a look at this!

**Comment by andreas-jonsson** [comment]
Yea. It would not work with a dual display setup.

I'm building my own with a custom config. The default one works well but throws an annoying POST error since I don't have a standard FDC. So I have to turn that of any way. :)

But it would probably be okay to use in the emu build as standard. I think 736k is usually more interesting then dual display for most emulators. :)

**Comment by andreas-jonsson** [comment]
Yea. It would not work with a dual display setup.

I'm building my own with a custom config. The default one works well but throws an annoying POST error since I don't have a standard FDC. So I have to turn that of any way. :)

But it would probably be okay to use in the emu build as standard. I think 736k is usually more interesting then dual display for most emulators. :)

**Comment by 640-KB** [comment]
@andreas-jonsson planning to include this in the next release 0.2.5. Great suggestion!

**Comment by andreas-jonsson** [comment]
Awesome! I'll help you test it. :)

**Comment by 640-KB** [comment]
Included in https://github.com/640-KB/GLaBIOS/commit/655bc338873f2775de00ca7a418bcc03c4052937

**Comment by andreas-jonsson** [comment]
Seems to work nicely. :)
Will include a new build of GLaBIOS in the next beta release of VirtualXT.

Thanks!
