### ISSUE TITLE
EMS support?

### ISSUE THREAD

**Issue by andreas-jonsson** [640-KB/GLaBIOS#40]
Hi!

Have you given EMS support any thoughts? I see you have worked a bit on the Intel Above board. :)

I currently emulate the [LoTech EMS 2MB board](https://texelec.com/product/lo-tech-ems-2-mb/). But lately with the addition of VGA support in VirtualXT I have been trying to minimize the conventional memory usage in the default image. So I have reduced the amount of drivers that are loaded by default. GLaTICK helps a lot, but it would also be very cool if we had a GLaMEM. ;)

Big thanks again for supplying GLaBIOS <3

**Comment by andreas-jonsson** [comment]
**Sidenote:**

Following some posts on your issue tracker I found the USE!UMBS driver. Had no idea that was a thing. :)
Will try it for my purpose and see if I can get it working.

**Comment by 640-KB** [comment]
Yes, USE!UMBS is awesome!  If you've got UMBs you can get what, up to 631K of free low memory?

Sorry I didn't respond on this one earlier.  So you are thinking perhaps we could wrap up a USE!UMBS or an EMS card's TSR drivers into an option ROM so move that code out of memory?  Since XMS/EMS drivers do exist as a DOS extension there would still need to be a TSR that loads since it does require registering the memory manager inside of DOS, so you'd still have the minimum size of a TSR (only 1k I think) even if you moved all of the code into ROM space.  It would also need to be a different ROM for each card likely too.

**Comment by andreas-jonsson** [comment]
> Since XMS/EMS drivers do exist as a DOS extension there would still need to be a TSR that loads since it does require registering the memory manager inside of DOS

Hmm.. yea.. kida make sense now when you mention it.
But does that need to be a TSR? Could it not be a regular application that shutdown after registering it? Since all the management code would be in ROM? I'm not super familiar with the API so I'm guessing here. :)

If not, then this is probably not a super big win since the EMS driver (at least for the LoTech card) is not that large.

**Comment by 640-KB** [comment]
So, while I think this sounds like a neat project, it seems like more something that would be best written as an option ROM (as there's virtually no room in the 8K BIOS now!). To be honest, it probably wouldn't make my short list of things to work on next...  Already have a list of things to get finished: extended keyboard, high density floppy and a maybe a real 286 version (sssshh, don't tell anyone yet :)).

Would it be okay to close this?

640KB

**Comment by andreas-jonsson** [comment]
> it seems like more something that would be best written as an option ROM

I always envisioned it as an option ROM. Just like GLaTICK.

> Would it be okay to close this?

Yes.
I don't think it is that high on the wishlist. At least not mine ;)

**Comment by 640-KB** [comment]
> > Would it be okay to close this?
> 
> Yes. I don't think it is that high on the wishlist. At least not mine ;)

It is a cool idea - thanks for suggesting it!  You can see my Issues list has a bit of back log of things I just need to finally get done! :)
