### ISSUE TITLE
.lst

### ISSUE THREAD

**Issue by folkertvanheusden** [640-KB/GLaBIOS#42]
Hi,

Please consider including the .lst for each .rom-file, e.g. the assembly listing annotated with all addresses and hexcodes.

**Comment by 640-KB** [comment]
Thanks for the suggestion, that makes sense -- I'll include those for future releases.  As there have become quite a few permutations for different build targets of the pre-built ROMs (close to 30 unique binaries) I may only include some of the more major ones.

In the meantime, here is the 5150 build from the current src with corresponding .lst file:

[GLABIOS_0.2.6_8P.zip](https://github.com/640-KB/GLaBIOS/files/13811065/GLABIOS_0.2.6_8P.zip)

Let me know if this works for you.

640KB

**Comment by folkertvanheusden** [comment]
Thanks a lot! That is exactly what I'm looking for - this is very useful while developing my emulator.
