### ISSUE TITLE
GlaBIOS for Triple D TD-20 industrial XT Mainboard

### ISSUE THREAD

**Issue by explit7** [640-KB/GLaBIOS#51]
Thats not an issue, rather a question:

I would like to test the GLaBIOS on my Triple D TD-20 Mainboard.

https://theretroweb.com/motherboards/s/triple-d-interna-td-20

The board is based on CityGate D20 ASIC which unites the most Glue Logic and some Xt Chips in one big ASIC.
82V54, 83C37A and 82C59A are implemented as standalone chips on this Mainboard.

Which Version should i use  to test?
![td-20-front-5ef8bd7f6e666462564258](https://github.com/640-KB/GLaBIOS/assets/11852348/a2b459ba-40ed-4446-9656-706f5cdfb30c)

**Comment by 640-KB** [comment]
Now that's an interesting board there... never seen that ASIC before!  I'd say use the [8T version](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.5/GLABIOS_0.2.5_8T.ROM) which should work fine, only perhaps the hotkeys that control the speed may not work if that chip does something differently.

Now, [if you don't have a floppy drive](https://forum.classic-computing.de/forum/index.php?thread/25113-xt-8088-td-20-mainboard/&postID=486712#post486712) there's a build option to make motherboard SW1 to set if you have a 0 floppies which is disabled on the 8T version by default, but here's a [new build](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.5/GLABIOS_0.2.6_8T_070324_IPLSW.ROM) that enables that if you don't want the error.... just flip switch SW1 and it shouldn't bug you about having no floppy.

Let me know how it goes.  Now I really need to find out more about this ASIC!

640KB

**Comment by explit7** [comment]
Thank you very much, @640-KB - This BIOS works like a charm! No Problems at all!
I think you can put the Mainboard on the List of supported Mainboards.

BTW: HEDAKA HED-918
https://theretroweb.com/motherboards/s/hedaka-hed-918

is 100% Clone of Triple D TD-20.
So your BIOS will also work on this Board.

**Comment by 640-KB** [comment]
> Thank you very much, @640-KB - This BIOS works like a charm! No Problems at all!
> I think you can put the Mainboard on the List of supported Mainboards.
> 
> BTW: HEDAKA HED-918
> https://theretroweb.com/motherboards/s/hedaka-hed-918
> 
> is 100% Clone of Triple D TD-20.
> So your BIOS will also work on this Board.
> ![GLABios](https://github.com/640-KB/GLaBIOS/assets/11852348/f054729c-1fbe-4f57-beae-4643dad0289a)
> 
> 

Excellent - glad to hear! I will definitely keep an eye out for one of these boards. If you ever come across a datasheet for that chipset, please send it my way in case there's any interesting features we could take advantage of in a GLaBIOS build for it.

640KB
