### ISSUE TITLE
More feature/enchancement recommendations....

### ISSUE THREAD

**Issue by Maxx1234** [640-KB/GLaBIOS#7]
1.Enchanced  (101-key) keyboard support [like Super PC/Turbo XT BIOS v3.1 (http://www.phatcode.net/downloads.php?id=101), which works almost flawlessly with Dave's Dev Lab AT2XT Keyboard Adapter (https://hackaday.io/project/166433-at2xt-keyboard-adapter) with RT01 firmware (http://pontacko.tfn-clan.de/files/at2xt/XTATKEY_RT01.ZIP)].

2.Option to completely disable the software turbo switch function.
Some boards (e.g. Fujitech Jumbo Turbo Board, DTK PIM-TB10-Z Rev.9) boot at normal speed although are jumpered to boot at turbo speed when using GLaBIOS.  With Super PC/Turbo XT BIOS v3.1, when turbo options are disabled (i.e. "commented"), the boards boot at turbo speed as expected.  Also, when loading the Lo-tech EMS driver, these boards switch speed mode (turbo <-> normal) if software turbo switch function is present in Super PC/Turbo XT BIOS v3.1.

Thank you for your hard work and prompt responses!!!

**Comment by 640-KB** [comment]
> 1.Enchanced (101-key) keyboard support [like Super PC/Turbo XT BIOS v3.1 (http://www.phatcode.net/downloads.php?id=101), which works almost flawlessly with Dave's Dev Lab AT2XT Keyboard Adapter (https://hackaday.io/project/166433-at2xt-keyboard-adapter) with RT01 firmware (http://pontacko.tfn-clan.de/files/at2xt/XTATKEY_RT01.ZIP)].

Yes, that's on my future enhancement list as well.

> 2.Option to completely disable the software turbo switch function. Some boards (e.g. Fujitech Jumbo Turbo Board, DTK PIM-TB10-Z Rev.9) boot at normal speed although are jumpered to boot at turbo speed when using GLaBIOS. With Super PC/Turbo XT BIOS v3.1, when turbo options are disabled (i.e. "commented"), the boards boot at turbo speed as expected. Also, when loading the Lo-tech EMS driver, these boards switch speed mode (turbo <-> normal) if software turbo switch function is present in Super PC/Turbo XT BIOS v3.1.

There is a build option that lets you decide which speed to boot into, which by default is TURBO for the "8088/V20" build and NORMAL for the others. 

```
	IF ARCH_TYPE EQ ARCH_TURBO
BOOT_SPEED		EQU	BOOT_TURBO
	ELSE
BOOT_SPEED		EQU	BOOT_NORMAL
	ENDIF
```

Can you try booting the ["5160" version of the ROM](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.5/GLABIOS_0.1.5_090622_5160.ROM) and see if that alters the behavior the way you need it?  If so, then changing that `BOOT_SPEED` build option will do the trick.  

FWIW I have found that some boards seem to have odd behavior with bootup "speed".  For example, my 8MHz "vintage" Turbo board has a jumper that when jumpered will lock it in high speed, despite the LED changing when you toggle the speed (good reminder to go back and re-test this).  So yeah, the more data points I can get for making this work right for as many boards as possible!

**Comment by 640-KB** [comment]
> Clarification: indeed, it boots into normal speed, but the ctrl-alt-+ hot key does work.
> When using the 5160 version, the system boots at the expected speed (i.e. based on the hardware turbo switch setting) and of course the software turbo switch function does not work. 

Got it - that confirms my theory that the overall speed part is working, it's just backwards to what you expect.  

> Nevertheless, when the Lo-tech EMS driver loads, the turbo state is switched. When the driver completes counting the EMS pages, the initial turbo state is restored. I have found that this quirky behaviour does not exist with Super PC/Turbo XT BIOS v3.1 when compiled with TURBO_ENABLED, TURBO_BOOT, TURBO_HOTKEY disabled ("commented").

Here's the [Turbo version](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.5/GLABIOS_0.1.5_090622_8088_T.ROM) just with the TURBO/NORMAL startup speed swapped.  I'm wondering if it's really just a matter of different boards expecting the opposite of each other.  Let me know which one of these behaves the way you'd expect it to.  I'll do a little more research and see if I can figure out which way is "correct".  

> Of note, the software turbo switch "quirky" behaviour does not exist in Juko ST-12 boards (I will try to find some time to test GLaBIOS with such a board and report with the result).

That would be great!  Appreciate all of the testing!

**Comment by Maxx1234** [comment]
GLABIOS_0.1.5_090622_8088_T.ROM:
Board boot speed according to hardware switch setting.
Software turbo switch works as expected.
Lo-tech EMS driver temporarily swaps turbo state.

GLABIOS_0.1.5_090622_5160_T.ROM:
Board boot speed reverse to hardware switch setting.
Software turbo switch does not work as expected.
Lo-tech EMS driver permanently swaps turbo state.

Juko ST-12 board with GLABIOS_0.1.5_090622_V20.ROM:
Board boot speed according to hardware switch setting.
Software turbo switch does not work (can hear the "beep" sound, but speed does not change).
Lo-tech EMS driver does not affect turbo state at all.
Board seems to run stable.

Please let me know if any more testing is needed!

**Comment by 640-KB** [comment]
@Maxx1234 I did some more testing and the plot thickens.  I tested my board on several other ROM images and compiled results on [my board](https://theretroweb.com/motherboards/s/golden-star-tech-x%27golden-turbo):

| BIOS  | Boot Speed |
| ------------- | ------------- |
| GLaBIOS [8088 v0.1.5](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.5/GLABIOS_0.1.5_090622_8088.ROM) (standard)  | Boots Turbo, Keyboard switching works |
| Award V2.03 (came with board) | Boots Normal/Low, Keyboard switching works  |
| AMI (1/31/89) | Boots Normal/Low, Keyboard switching works  |
| Phoenix 2.51 | Boots Normal/Low, Keyboard switching works  |
| Super PC 3.1 | Boots Normal/Low, Keyboard switching does not work  |
| Turbo PC 3.1 | Boots Turbo, Keyboard switching works  |

I'm wondering if it was the case that these older BIOS'es booted to "Normal" (slow) speed by default and expected the user to go to Turbo if and only if their program can "handle it".  If that's the case, I'd guess a lot of these Turbo XT's ran well below their potential for most of their lives.  Or perhaps this is why there may be a difference in how these boards all worked - some generations defaulted to Normal and some to Turbo, effectively swapping the behavior of the BIOS'es.

On to yours:

> GLABIOS_0.1.5_090622_8088_T.ROM: Board boot speed according to hardware switch setting. Software turbo switch works as expected. Lo-tech EMS driver temporarily swaps turbo state.

So to confirm, this is what you would expect or want to happen?

> GLABIOS_0.1.5_090622_5160_T.ROM: Board boot speed reverse to hardware switch setting. Software turbo switch does not work as expected. Lo-tech EMS driver permanently swaps turbo state.

Okay, that confirms what I had expected. Very helpful.

> Juko ST-12 board with GLABIOS_0.1.5_090622_V20.ROM: Board boot speed according to hardware switch setting. Software turbo switch does not work (can hear the "beep" sound, but speed does not change). Lo-tech EMS driver does not affect turbo state at all. Board seems to run stable.

Does software/keyboard turbo switch work on _any_ BIOS or does the hardware switch always choose?

**Comment by Maxx1234** [comment]
_GLABIOS_0.1.5_090622_8088_T.ROM_
### So to confirm, this is what you would expect or want to happen?
More or less yes.
Lo-tech EMS driver temporarily swapping turbo state presents a minor nuisance.


_GLABIOS_0.1.5_090622_5160_T.ROM_
### Okay, that confirms what I had expected. And is this the same as the Super/Turbo BIOS if you disable all of the TURBO* build options?
1.With Super/Turbo BIOS TURBO* build options ENABLED:
Board boot speed reverse to hardware switch setting.
Software turbo switch works as expected.
Lo-tech EMS driver temporarily swaps turbo state.
2.With Super/Turbo BIOS TURBO* build options ENABLE:
Board boot speed according to hardware switch setting.
Software turbo switch does not work.
Lo-tech EMS driver does not affect turbo state at all.

_Juko ST-12 board with GLABIOS_0.1.5_090622_V20.ROM_
### Does software/keyboard turbo switch work on any BIOS or does the hardware switch always choose?
Super/Turbo BIOS TURBO* build options ENABLED -> software/keyboard turbo switch does not work ("beep" sound heard)
Super/Turbo BIOS TURBO* build options DISABLED -> software/keyboard turbo switch does not work ("beep" sound not heard)
JUKO/NEL BIOS v2.32 ->  -> software/keyboard turbo switch does not work ("beep" sound not heard)
This board appears to require a TSR ("STURBO.COM") to enable software turbo switching:_

> . Change Mother Board's speed


                        The program "STURBO.COM" is used to change 
                   the speed of the mother Board, and to set the 
                   board's speed during disk access.


                   STURBO [switch]  [disk access speed control]

                   where  [switch] = ON    turbo mode  (high speed)
                                   = OFF   normal mode (low speed)
	                           = HARD  hard switch dependent
		
      [disk access speed control]  =  /t  :  high speed
	                           =  /n  :  low speed
	     

                   

                        Once the "STURBO.COM" is run. You can use 
                   keyboard to switch the speed of the board.


                   Press 'alt' 'ctl' '+' at the same time for high speed.

                   Press 'alt' 'ctl' '-' at the same time for low speed.

                   Press 'alt' 'ctl' '*' at the same time for hard
                                         switch dependent.

                   note :  The '+', '-', and '*' are the keys in
                           in the key pad.

**Comment by 640-KB** [comment]
@Maxx1234 If you have a moment, would you mind trying [this ROM](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.5/GLABIOS_0.1.5_090822_V20_J.ROM) on your ST-12 and see if the keyboard (ctrl-alt-+) toggles the speed?

**Comment by 640-KB** [comment]
> Please let me know if any more testing is needed!

Do you have the ST-12 with V20, clocked at the full 12MHz?  Are you using (or do you have to test) a "standard" floppy drive controller (360K, no controller BIOS) that you could test floppy drive functions at that speed?  Read, Write, Format and maybe boot.  I've only been able to test up to 8MHz (on real hardware) so would be great to know if all of the speed tunings are working fine at that speed.

Thanks again for all of the help!  Really appreciate it!

**Comment by Maxx1234** [comment]
I have  the ST-12 with V20 + 8087 @ 12MHz, also a "standard" FDC.  I think that I also have a 360K 5.25" drive along with some floppies (if this is not the case, I must use my Gotek FDD emulator with FlashFloppy firmware).
I will report back tomorrow when I have physical access to the system.

Glad to help!

**Comment by 640-KB** [comment]
> I have the ST-12 with V20 + 8087 @ 12MHz, also a "standard" FDC. I think that I also have a 360K 5.25" drive along with some floppies (if this is not the case, I must use my Gotek FDD emulator with FlashFloppy firmware). I will report back tomorrow when I have physical access to the system.

What an awesome system!  I'm jealous!

**Comment by Maxx1234** [comment]
> @Maxx1234 If you have a moment, would you mind trying [this ROM](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.5/GLABIOS_0.1.5_090822_V20_J.ROM) on your ST-12 and see if the keyboard (ctrl-alt-+) toggles the speed?

The BIOS works but there is no turbo mode switch, even though I can hear the "beep" when ctrl-alt-+ is pressed,

**Comment by Maxx1234** [comment]
> > Please let me know if any more testing is needed!
> 
> Do you have the ST-12 with V20, clocked at the full 12MHz? Are you using (or do you have to test) a "standard" floppy drive controller (360K, no controller BIOS) that you could test floppy drive functions at that speed? Read, Write, Format and maybe boot. I've only been able to test up to 8MHz (on real hardware) so would be great to know if all of the speed tunings are working fine at that speed.
> 
> Thanks again for all of the help! Really appreciate it!

Tested with a "standard" FDC, a 5.25" FDD and a 360K floppy.  None of 5160/8088/V20 BIOSes work (boot failure, cannot format, cannot display disk contents).  No option ROMs (HDC,FDC) present.
The system works fine with Super PC/Turbo XT BIOS....

**Comment by 640-KB** [comment]
> Tested with a "standard" FDC, a 5.25" FDD and a 360K floppy. None of 5160/8088/V20 BIOSes work (boot failure, cannot format, cannot display disk contents). No option ROMs (HDC,FDC) present. 

And it gives a seek error or something like that on POST?  Can you try [this ROM](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.3/GLABIOS_0.1.5_090822_V20_J2.ROM)?

**Comment by 640-KB** [comment]
> The BIOS works but there is no turbo mode switch, even though I can hear the "beep" when ctrl-alt-+ is pressed,

Are you able to run DOS DEBUG.EXE on it?  If so, can you run it and at the "-" prompt type: "i 90" (no quotes) and see what it says?

**Comment by Maxx1234** [comment]
> > Tested with a "standard" FDC, a 5.25" FDD and a 360K floppy. None of 5160/8088/V20 BIOSes work (boot failure, cannot format, cannot display disk contents). No option ROMs (HDC,FDC) present.
> 
> And it gives a seek error or something like that on POST? Can you try [this ROM](https://github.com/640-KB/GLaBIOS/releases/download/v0.1.3/GLABIOS_0.1.5_090822_V20_J2.ROM)?

I guess it is seek errors during dir/format.  "Boot disk fail" during POST.  Same behaviour with GLABIOS_0.1.5_090822_V20_J2.ROM.

**Comment by Maxx1234** [comment]
> > The BIOS works but there is no turbo mode switch, even though I can hear the "beep" when ctrl-alt-+ is pressed,
> 
> Are you able to run DOS DEBUG.EXE on it? If so, can you run it and at the "-" prompt type: "i 90" (no quotes) and see what it says?

I get "00" (no quotes)

**Comment by 640-KB** [comment]
Closing and separating items into new Issues
